/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GestionMedicos;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge Custodio
 */
public class Main extends javax.swing.JPanel {
    ArrayList<Medico> Medicos = new ArrayList<Medico>();
    /**
     * Creates new form Main
     */
    Metodos meth = new Metodos();
    public Main() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_medico = new javax.swing.JLabel();
        sep_top = new javax.swing.JSeparator();
        txt_nif = new javax.swing.JTextField();
        lbl_nif = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        lbl_nombre = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JTextField();
        lbl_nif2 = new javax.swing.JLabel();
        txt_especialidad = new javax.swing.JTextField();
        lbl_nif3 = new javax.swing.JLabel();
        btn_nuevo = new javax.swing.JButton();
        sep_bot = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btn_mostrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        lbl_medico.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_medico.setForeground(new java.awt.Color(0, 0, 0));
        lbl_medico.setText("Médico");
        lbl_medico.setToolTipText("");
        lbl_medico.setName("lblMedico"); // NOI18N

        sep_top.setBackground(new java.awt.Color(153, 153, 153));
        sep_top.setForeground(new java.awt.Color(153, 153, 153));

        lbl_nif.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_nif.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nif.setText("Nif:");
        lbl_nif.setToolTipText("");

        lbl_nombre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_nombre.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nombre.setText("Nombre:");
        lbl_nombre.setToolTipText("");

        txt_apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidosActionPerformed(evt);
            }
        });

        lbl_nif2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_nif2.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nif2.setText("Apellidos:");
        lbl_nif2.setToolTipText("");

        lbl_nif3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_nif3.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nif3.setText("Especialidad:");
        lbl_nif3.setToolTipText("");

        btn_nuevo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btn_nuevo.setText("Nuevo");
        btn_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nuevoMouseClicked(evt);
            }
        });

        sep_bot.setBackground(new java.awt.Color(153, 153, 153));
        sep_bot.setForeground(new java.awt.Color(153, 153, 153));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btn_mostrar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btn_mostrar.setText("Mostrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(lbl_medico))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(97, 97, 97)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_nombre)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_nif)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_nif, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_nif2)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_nif3)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_nuevo))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(sep_top, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sep_bot, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_mostrar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbl_medico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sep_top, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nif)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btn_nuevo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nif2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nif3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sep_bot, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mostrar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidosActionPerformed

    private void btn_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nuevoMouseClicked
        Medico medico = new Medico();
        int validate = 0;
        if(meth.checkNIF(txt_nif.getText())!=null){
            medico.setNif(txt_nif.getText());    
            validate++;
        }
        if(meth.checkPersData(txt_nombre.getText())!=null){
            medico.setNombre(txt_nombre.getText());
            validate++;
        }
        if(meth.checkPersData(txt_apellidos.getText())!=null){
            medico.setNombre(txt_apellidos.getText());
            validate++;
        }
        if(meth.checkPersData(txt_especialidad.getText())!=null){
            medico.setNombre(txt_especialidad.getText());
            validate++;
        }
        if(validate==4){
            Medicos.add(medico);
        }else{
            JOptionPane.showMessageDialog(lbl_nombre, "Los datos requeridos no son adecuados, por favor revise.");
        }
    }//GEN-LAST:event_btn_nuevoMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mostrar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_medico;
    private javax.swing.JLabel lbl_nif;
    private javax.swing.JLabel lbl_nif2;
    private javax.swing.JLabel lbl_nif3;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JSeparator sep_bot;
    private javax.swing.JSeparator sep_top;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_especialidad;
    private javax.swing.JTextField txt_nif;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
