/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reservas;

import java.awt.Dialog;
import javax.swing.JDialog;

/**
 *
 * @author soyel
 */
public class Menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_principal
     */
    public Menu_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diag_reservas = new javax.swing.JDialog();
        jpan_reservas = new javax.swing.JPanel();
        lbl_titulo1 = new javax.swing.JLabel();
        jpan_datospersonales = new javax.swing.JPanel();
        lbl_nombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        lbl_apellidos = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JTextField();
        lbl_telefono = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        jpan_datosreserva = new javax.swing.JPanel();
        lbl_fecha = new javax.swing.JLabel();
        spn_fecha = new javax.swing.JSpinner();
        lbl_tipoevento = new javax.swing.JLabel();
        cmb_tipoevento = new javax.swing.JComboBox<>();
        lbl_numasistentes = new javax.swing.JLabel();
        cmb_numasistentes = new javax.swing.JComboBox<>();
        lbl_tipococina = new javax.swing.JLabel();
        cmb_tipococina = new javax.swing.JComboBox<>();
        jpan_detallescongreso = new javax.swing.JPanel();
        lbl_numjornadas = new javax.swing.JLabel();
        spn_numjornadas = new javax.swing.JSpinner();
        lbl_habitaciones = new javax.swing.JLabel();
        rbtn_hab_si = new javax.swing.JRadioButton();
        rbtn_hab_no = new javax.swing.JRadioButton();
        btn_reservar1 = new javax.swing.JButton();
        btng_habitaciones = new javax.swing.ButtonGroup();
        lbl_titulo = new javax.swing.JLabel();
        lbl_subtitulo = new javax.swing.JLabel();
        btn_reservar = new javax.swing.JButton();
        lbl_imagenhotel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        men_reservas = new javax.swing.JMenu();
        mit_resv_salon = new javax.swing.JMenuItem();
        mit_salir = new javax.swing.JMenuItem();

        diag_reservas.setTitle("BK Hoteles");
        diag_reservas.setBounds(new java.awt.Rectangle(600, 200, 0, 0));
        diag_reservas.setName("diag_reservas"); // NOI18N

        jpan_reservas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jpan_reservas.setName("jpan_reservas"); // NOI18N

        lbl_titulo1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_titulo1.setText("Para reservar el Salón Habana por favor rellene los siguientes datos:");
        lbl_titulo1.setName("lbl_titulo"); // NOI18N

        jpan_datospersonales.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos personales"));
        jpan_datospersonales.setName("jpan_datospersonales"); // NOI18N

        lbl_nombre.setText("Nombre:");
        lbl_nombre.setDoubleBuffered(true);
        lbl_nombre.setName("lbl_nombre"); // NOI18N

        txt_nombre.setToolTipText("Introduzca su nombre");
        txt_nombre.setName("txt_nombre"); // NOI18N

        lbl_apellidos.setText("Apellidos:");

        txt_apellidos.setToolTipText("Introduzca sus apellidos");
        txt_apellidos.setName("txt_apellidos"); // NOI18N

        lbl_telefono.setText("Telefono:");
        lbl_telefono.setName("lbl_telefono"); // NOI18N

        txt_telefono.setToolTipText("Introduzca su teléfono");
        txt_telefono.setName("txt_telefono"); // NOI18N

        javax.swing.GroupLayout jpan_datospersonalesLayout = new javax.swing.GroupLayout(jpan_datospersonales);
        jpan_datospersonales.setLayout(jpan_datospersonalesLayout);
        jpan_datospersonalesLayout.setHorizontalGroup(
            jpan_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_datospersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpan_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nombre)
                    .addComponent(lbl_apellidos)
                    .addComponent(lbl_telefono))
                .addGap(18, 18, 18)
                .addGroup(jpan_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(txt_apellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(txt_telefono))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpan_datospersonalesLayout.setVerticalGroup(
            jpan_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_datospersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpan_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpan_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_apellidos)
                    .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpan_datospersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_telefono)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpan_datosreserva.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la reserva"));
        jpan_datosreserva.setName("jpan_datosreserva"); // NOI18N

        lbl_fecha.setText("Fecha de la reserva:");
        lbl_fecha.setName("lbl_fecha"); // NOI18N

        spn_fecha.setModel(new javax.swing.SpinnerDateModel());
        spn_fecha.setToolTipText("Indique la fecha de la reserva");
        spn_fecha.setName("spn_fecha"); // NOI18N

        lbl_tipoevento.setText("Tipo de evento:");
        lbl_tipoevento.setName("lbl_tipoevento"); // NOI18N

        cmb_tipoevento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banquete", "Jornada", "Congreso" }));
        cmb_tipoevento.setToolTipText("Indique el tipode evento");
        cmb_tipoevento.setName("cmb_tipoevento"); // NOI18N
        cmb_tipoevento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_tipoeventoItemStateChanged(evt);
            }
        });
        cmb_tipoevento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipoeventoActionPerformed(evt);
            }
        });

        lbl_numasistentes.setText("Número de asistentes:");
        lbl_numasistentes.setName("lbl_numasistentes"); // NOI18N

        cmb_numasistentes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1-10", "11-25", "26-100", "+100" }));
        cmb_numasistentes.setToolTipText("Indique el número de asistentes");
        cmb_numasistentes.setName("cmb_numasistentes"); // NOI18N

        lbl_tipococina.setText("Tipo de cocina:");
        lbl_tipococina.setName("lbl_tipococina"); // NOI18N

        cmb_tipococina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bufé", "Carta", "Pedir cita con el chef", "No precisa" }));
        cmb_tipococina.setToolTipText("Indique el tipo de cocina");
        cmb_tipococina.setName("cmb_tipococina"); // NOI18N

        jpan_detallescongreso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalles para congreso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N
        jpan_detallescongreso.setName("jpan_detallecongreso"); // NOI18N
        jpan_detallescongreso.setVisible(false);

        lbl_numjornadas.setText("Número de jornadas");
        lbl_numjornadas.setName("lbl_numjornadas"); // NOI18N

        spn_numjornadas.setToolTipText("Indique el número de jornadas");
        spn_numjornadas.setName("spn_numjornadas"); // NOI18N

        lbl_habitaciones.setText("¿Precisan habitaciones?");
        lbl_habitaciones.setName("lbl_habitaciones"); // NOI18N

        btng_habitaciones.add(rbtn_hab_si);
        rbtn_hab_si.setText("Si");
        rbtn_hab_si.setToolTipText("Marque para confirmar la necesidad de habitaciones");
        rbtn_hab_si.setName("rbtn_hab_si"); // NOI18N

        btng_habitaciones.add(rbtn_hab_no);
        rbtn_hab_no.setToolTipText("Maque si no necesitan habitaciones");
        rbtn_hab_no.setLabel("No");
        rbtn_hab_no.setName("rbtn_hab_no"); // NOI18N

        javax.swing.GroupLayout jpan_detallescongresoLayout = new javax.swing.GroupLayout(jpan_detallescongreso);
        jpan_detallescongreso.setLayout(jpan_detallescongresoLayout);
        jpan_detallescongresoLayout.setHorizontalGroup(
            jpan_detallescongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_detallescongresoLayout.createSequentialGroup()
                .addGroup(jpan_detallescongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpan_detallescongresoLayout.createSequentialGroup()
                        .addComponent(lbl_numjornadas)
                        .addGap(38, 38, 38)
                        .addComponent(spn_numjornadas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpan_detallescongresoLayout.createSequentialGroup()
                        .addComponent(lbl_habitaciones)
                        .addGap(18, 18, 18)
                        .addComponent(rbtn_hab_si)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtn_hab_no)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpan_detallescongresoLayout.setVerticalGroup(
            jpan_detallescongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_detallescongresoLayout.createSequentialGroup()
                .addGroup(jpan_detallescongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_numjornadas)
                    .addComponent(spn_numjornadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpan_detallescongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_habitaciones)
                    .addComponent(rbtn_hab_si)
                    .addComponent(rbtn_hab_no))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpan_datosreservaLayout = new javax.swing.GroupLayout(jpan_datosreserva);
        jpan_datosreserva.setLayout(jpan_datosreservaLayout);
        jpan_datosreservaLayout.setHorizontalGroup(
            jpan_datosreservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_datosreservaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpan_datosreservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_fecha)
                    .addComponent(lbl_tipoevento)
                    .addComponent(lbl_numasistentes)
                    .addComponent(lbl_tipococina))
                .addGap(18, 18, 18)
                .addGroup(jpan_datosreservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spn_fecha)
                    .addComponent(cmb_tipoevento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_numasistentes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_tipococina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(jpan_datosreservaLayout.createSequentialGroup()
                .addComponent(jpan_detallescongreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpan_datosreservaLayout.setVerticalGroup(
            jpan_datosreservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_datosreservaLayout.createSequentialGroup()
                .addGroup(jpan_datosreservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fecha)
                    .addComponent(spn_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpan_datosreservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tipoevento)
                    .addComponent(cmb_tipoevento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpan_datosreservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_numasistentes)
                    .addComponent(cmb_numasistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpan_datosreservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tipococina)
                    .addComponent(cmb_tipococina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpan_detallescongreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btn_reservar1.setText("Reservar");
        btn_reservar1.setToolTipText("Pulse para reservar");
        btn_reservar1.setName("btn_reservar"); // NOI18N
        btn_reservar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reservar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpan_reservasLayout = new javax.swing.GroupLayout(jpan_reservas);
        jpan_reservas.setLayout(jpan_reservasLayout);
        jpan_reservasLayout.setHorizontalGroup(
            jpan_reservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_reservasLayout.createSequentialGroup()
                .addGroup(jpan_reservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpan_reservasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpan_datospersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpan_reservasLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btn_reservar1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpan_reservasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpan_reservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpan_datosreserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpan_reservasLayout.setVerticalGroup(
            jpan_reservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_reservasLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbl_titulo1)
                .addGap(18, 18, 18)
                .addComponent(jpan_datospersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpan_datosreserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_reservar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout diag_reservasLayout = new javax.swing.GroupLayout(diag_reservas.getContentPane());
        diag_reservas.getContentPane().setLayout(diag_reservasLayout);
        diag_reservasLayout.setHorizontalGroup(
            diag_reservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diag_reservasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpan_reservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        diag_reservasLayout.setVerticalGroup(
            diag_reservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_reservasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpan_reservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BK Hoteles");
        setBounds(new java.awt.Rectangle(600, 200, 0, 0));
        setIconImages(null);
        setName("frm_main"); // NOI18N
        setResizable(false);

        lbl_titulo.setFont(new java.awt.Font("DejaVu Serif", 0, 24)); // NOI18N
        lbl_titulo.setText("Bienvenidos a BK Hoteles");
        lbl_titulo.setName("lbl_titulo"); // NOI18N

        lbl_subtitulo.setFont(new java.awt.Font("DejaVu Serif", 0, 18)); // NOI18N
        lbl_subtitulo.setText("¿En qué podemos ayudarle?");
        lbl_subtitulo.setName("lbl_subtitulo"); // NOI18N

        btn_reservar.setText("Reservar Salón Habana");
        btn_reservar.setToolTipText("Pulse para iniciar la reserva del Salón Habana");
        btn_reservar.setName("btn_reservar"); // NOI18N
        btn_reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reservarActionPerformed(evt);
            }
        });

        lbl_imagenhotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reservas/res/hotel.jpg"))); // NOI18N
        lbl_imagenhotel.setName("lbl_imagenhotel"); // NOI18N

        men_reservas.setText("Reservas");
        men_reservas.setName("men_reservas"); // NOI18N

        mit_resv_salon.setText("Reservar Salón Habana");
        mit_resv_salon.setName("mit_resv_salon"); // NOI18N
        mit_resv_salon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mit_resv_salonActionPerformed(evt);
            }
        });
        men_reservas.add(mit_resv_salon);

        mit_salir.setText("Salir");
        mit_salir.setName("mit_salir"); // NOI18N
        mit_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mit_salirActionPerformed(evt);
            }
        });
        men_reservas.add(mit_salir);

        jMenuBar1.add(men_reservas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(lbl_subtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_reservar, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbl_imagenhotel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbl_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_subtitulo)
                .addGap(18, 18, 18)
                .addComponent(btn_reservar)
                .addGap(49, 49, 49)
                .addComponent(lbl_imagenhotel, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_reservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reservarActionPerformed
        // TODO add your handling code here:
        /*Reservas reservas_frm;
        reservas_frm = new Reservas();
        reservas_frm.setVisible(true);*/
        diag_reservas.setSize(450,600);
        diag_reservas.setModal(true);
        diag_reservas.setVisible(true);
        
                
    }//GEN-LAST:event_btn_reservarActionPerformed

    private void cmb_tipoeventoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_tipoeventoItemStateChanged
        // TODO add your handling code here:
        jpan_detallescongreso.setVisible("Congreso".equals(evt.getItem().toString()));
    }//GEN-LAST:event_cmb_tipoeventoItemStateChanged

    private void btn_reservar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reservar1ActionPerformed
        // TODO add your handling code here:
        diag_reservas.dispose();
    }//GEN-LAST:event_btn_reservar1ActionPerformed

    private void mit_resv_salonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mit_resv_salonActionPerformed
        // TODO add your handling code here:
        diag_reservas.setSize(450,600);
        diag_reservas.setModal(true);
        diag_reservas.setVisible(true);
    }//GEN-LAST:event_mit_resv_salonActionPerformed

    private void mit_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mit_salirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_mit_salirActionPerformed

    private void cmb_tipoeventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipoeventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tipoeventoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_principal().setVisible(true);
            }
        });
        /* Código para que arranque el menu en jdk 1.8
        java.awt.EventQueue.invokeLater(() -> {
            new Menu_principal().setVisible(true);
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reservar;
    private javax.swing.JButton btn_reservar1;
    private javax.swing.ButtonGroup btng_habitaciones;
    private javax.swing.JComboBox<String> cmb_numasistentes;
    private javax.swing.JComboBox<String> cmb_tipococina;
    private javax.swing.JComboBox<String> cmb_tipoevento;
    private javax.swing.JDialog diag_reservas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jpan_datospersonales;
    private javax.swing.JPanel jpan_datosreserva;
    private javax.swing.JPanel jpan_detallescongreso;
    private javax.swing.JPanel jpan_reservas;
    private javax.swing.JLabel lbl_apellidos;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_habitaciones;
    private javax.swing.JLabel lbl_imagenhotel;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_numasistentes;
    private javax.swing.JLabel lbl_numjornadas;
    private javax.swing.JLabel lbl_subtitulo;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JLabel lbl_tipococina;
    private javax.swing.JLabel lbl_tipoevento;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_titulo1;
    private javax.swing.JMenu men_reservas;
    private javax.swing.JMenuItem mit_resv_salon;
    private javax.swing.JMenuItem mit_salir;
    private javax.swing.JRadioButton rbtn_hab_no;
    private javax.swing.JRadioButton rbtn_hab_si;
    private javax.swing.JSpinner spn_fecha;
    private javax.swing.JSpinner spn_numjornadas;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
